// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
lv_obj_t * ui_Screen1;

//Label definition
lv_obj_t * ui_Label1;
lv_obj_t * ui_Label2;
lv_obj_t * ui_Label3;
lv_obj_t * ui_Label4;
lv_obj_t * ui_Label5;
lv_obj_t * ui_Label6;
lv_obj_t * ui_Label7;
lv_obj_t * ui_Label8;
lv_obj_t * ui_Label9;
lv_obj_t * ui_Label10;
lv_obj_t * ui_Label11;
lv_obj_t * ui_Label12;
lv_obj_t * ui_Label13;
lv_obj_t * ui_Label14;
lv_obj_t * ui_Label15;
lv_obj_t * ui_Label16;
lv_obj_t * ui_Label17;
lv_obj_t * ui_Label18;
lv_obj_t * ui_Label19;
lv_obj_t * ui_Label20;

//İmage definition
lv_obj_t * ui_Image1;
lv_obj_t * ui_Image2;
lv_obj_t * ui_Image3;
lv_obj_t * ui_Image4;
lv_obj_t * ui_Image5;
lv_obj_t * ui_Image6;
lv_obj_t * ui_Image7;
lv_obj_t * ui_Image8;
lv_obj_t * ui_Image9;
lv_obj_t * ui_Image10;
lv_obj_t * ui_Image11;
lv_obj_t * ui_Image12;
lv_obj_t * ui_Image13;
lv_obj_t * ui_Image14;
lv_obj_t * ui_Image15;

// slider definition
lv_obj_t * ui_Slider1;
lv_obj_t * ui_Slider2;
lv_obj_t * ui_Slider3;
lv_obj_t * ui_Slider4;
lv_obj_t * ui_Slider5;
lv_obj_t * ui_Slider6;
lv_obj_t * ui_Slider7;
lv_obj_t * ui_Slider8;
lv_obj_t * ui_Slider9;
lv_obj_t * ui_Slider10;

// arc definition
lv_obj_t * ui_Arc1;
lv_obj_t * ui_Arc2;
lv_obj_t * ui_Arc3;
lv_obj_t * ui_Arc4;
lv_obj_t * ui_Arc5;
lv_obj_t * ui_Arc6;
lv_obj_t * ui_Arc7;
lv_obj_t * ui_Arc8;
lv_obj_t * ui_Arc9;
lv_obj_t * ui_Arc10;

// panel init
lv_obj_t * ui_Panel1;
lv_obj_t * ui_Panel2;
lv_obj_t * ui_Panel3;
lv_obj_t * ui_Panel4;
lv_obj_t * ui_Panel5;
lv_obj_t * ui_Panel6;
lv_obj_t * ui_Panel7;
lv_obj_t * ui_Panel8;
lv_obj_t * ui_Panel9;
lv_obj_t * ui_Panel10;

// container init
lv_obj_t * ui_Container1;
lv_obj_t * ui_Container2;
lv_obj_t * ui_Container3;
lv_obj_t * ui_Container4;
lv_obj_t * ui_Container5;
lv_obj_t * ui_Container6;
lv_obj_t * ui_Container7;
lv_obj_t * ui_Container8;
lv_obj_t * ui_Container9;
lv_obj_t * ui_Container10;


// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
lv_obj_t * ui_Screen2;
// Label definition
lv_obj_t * ui_Label21;
lv_obj_t * ui_Label22;
lv_obj_t * ui_Label23;
lv_obj_t * ui_Label24;
lv_obj_t * ui_Label25;
lv_obj_t * ui_Label26;
lv_obj_t * ui_Label27;
lv_obj_t * ui_Label28;
lv_obj_t * ui_Label29;
lv_obj_t * ui_Label30;
lv_obj_t * ui_Label31;
lv_obj_t * ui_Label32;
lv_obj_t * ui_Label33;
lv_obj_t * ui_Label34;
lv_obj_t * ui_Label35;
lv_obj_t * ui_Label36;
lv_obj_t * ui_Label37;
lv_obj_t * ui_Label38;
lv_obj_t * ui_Label39;
lv_obj_t * ui_Label40;

// Image definition
lv_obj_t * ui_Image16;
lv_obj_t * ui_Image17;
lv_obj_t * ui_Image18;
lv_obj_t * ui_Image19;
lv_obj_t * ui_Image20;
lv_obj_t * ui_Image21;
lv_obj_t * ui_Image22;
lv_obj_t * ui_Image23;
lv_obj_t * ui_Image24;
lv_obj_t * ui_Image25;
lv_obj_t * ui_Image26;
lv_obj_t * ui_Image27;
lv_obj_t * ui_Image28;
lv_obj_t * ui_Image29;
lv_obj_t * ui_Image30;

// slider definition
lv_obj_t * ui_Slider11;
lv_obj_t * ui_Slider12;
lv_obj_t * ui_Slider13;
lv_obj_t * ui_Slider14;
lv_obj_t * ui_Slider15;
lv_obj_t * ui_Slider16;
lv_obj_t * ui_Slider17;
lv_obj_t * ui_Slider18;
lv_obj_t * ui_Slider19;
lv_obj_t * ui_Slider20;

// arc definition
lv_obj_t * ui_Arc11;
lv_obj_t * ui_Arc12;
lv_obj_t * ui_Arc13;
lv_obj_t * ui_Arc14;
lv_obj_t * ui_Arc15;
lv_obj_t * ui_Arc16;
lv_obj_t * ui_Arc17;
lv_obj_t * ui_Arc18;
lv_obj_t * ui_Arc19;
lv_obj_t * ui_Arc20;

// panel init
lv_obj_t * ui_Panel11;
lv_obj_t * ui_Panel12;
lv_obj_t * ui_Panel13;
lv_obj_t * ui_Panel14;
lv_obj_t * ui_Panel15;
lv_obj_t * ui_Panel16;
lv_obj_t * ui_Panel17;
lv_obj_t * ui_Panel18;
lv_obj_t * ui_Panel19;
lv_obj_t * ui_Panel20;

// container init
lv_obj_t * ui_Container11;
lv_obj_t * ui_Container12;
lv_obj_t * ui_Container13;
lv_obj_t * ui_Container14;
lv_obj_t * ui_Container15;
lv_obj_t * ui_Container16;
lv_obj_t * ui_Container17;
lv_obj_t * ui_Container18;
lv_obj_t * ui_Container19;
lv_obj_t * ui_Container20;

// SCREEN: ui_Screen3
void ui_Screen3_screen_init(void);
lv_obj_t * ui_Screen3;

// Label definition
lv_obj_t * ui_Label41;
lv_obj_t * ui_Label42;
lv_obj_t * ui_Label43;
lv_obj_t * ui_Label44;
lv_obj_t * ui_Label45;
lv_obj_t * ui_Label46;
lv_obj_t * ui_Label47;
lv_obj_t * ui_Label48;
lv_obj_t * ui_Label49;
lv_obj_t * ui_Label50;
lv_obj_t * ui_Label51;
lv_obj_t * ui_Label52;
lv_obj_t * ui_Label53;
lv_obj_t * ui_Label54;
lv_obj_t * ui_Label55;
lv_obj_t * ui_Label56;
lv_obj_t * ui_Label57;
lv_obj_t * ui_Label58;
lv_obj_t * ui_Label59;
lv_obj_t * ui_Label60;

// Image definition
lv_obj_t * ui_Image31;
lv_obj_t * ui_Image32;
lv_obj_t * ui_Image33;
lv_obj_t * ui_Image34;
lv_obj_t * ui_Image35;
lv_obj_t * ui_Image36;
lv_obj_t * ui_Image37;
lv_obj_t * ui_Image38;
lv_obj_t * ui_Image39;
lv_obj_t * ui_Image40;
lv_obj_t * ui_Image41;
lv_obj_t * ui_Image42;
lv_obj_t * ui_Image43;
lv_obj_t * ui_Image44;
lv_obj_t * ui_Image45;


// slider definition
lv_obj_t * ui_Slider21;
lv_obj_t * ui_Slider22;
lv_obj_t * ui_Slider23;
lv_obj_t * ui_Slider24;
lv_obj_t * ui_Slider25;
lv_obj_t * ui_Slider26;
lv_obj_t * ui_Slider27;
lv_obj_t * ui_Slider28;
lv_obj_t * ui_Slider29;
lv_obj_t * ui_Slider30;

// arc definition
lv_obj_t * ui_Arc21;
lv_obj_t * ui_Arc22;
lv_obj_t * ui_Arc23;
lv_obj_t * ui_Arc24;
lv_obj_t * ui_Arc25;
lv_obj_t * ui_Arc26;
lv_obj_t * ui_Arc27;
lv_obj_t * ui_Arc28;
lv_obj_t * ui_Arc29;
lv_obj_t * ui_Arc30;

// panel init
lv_obj_t * ui_Panel21;
lv_obj_t * ui_Panel22;
lv_obj_t * ui_Panel23;
lv_obj_t * ui_Panel24;
lv_obj_t * ui_Panel25;
lv_obj_t * ui_Panel26;
lv_obj_t * ui_Panel27;
lv_obj_t * ui_Panel28;
lv_obj_t * ui_Panel29;
lv_obj_t * ui_Panel30;

// container init
lv_obj_t * ui_Container21;
lv_obj_t * ui_Container22;
lv_obj_t * ui_Container23;
lv_obj_t * ui_Container24;
lv_obj_t * ui_Container25;
lv_obj_t * ui_Container26;
lv_obj_t * ui_Container27;
lv_obj_t * ui_Container28;
lv_obj_t * ui_Container29;
lv_obj_t * ui_Container30;


// SCREEN: ui_Screen4
void ui_Screen4_screen_init(void);
lv_obj_t * ui_Screen4;

// Label definition
lv_obj_t * ui_Label61;
lv_obj_t * ui_Label62;
lv_obj_t * ui_Label63;
lv_obj_t * ui_Label64;
lv_obj_t * ui_Label65;
lv_obj_t * ui_Label66;
lv_obj_t * ui_Label67;
lv_obj_t * ui_Label68;
lv_obj_t * ui_Label69;
lv_obj_t * ui_Label70;
lv_obj_t * ui_Label71;
lv_obj_t * ui_Label72;
lv_obj_t * ui_Label73;
lv_obj_t * ui_Label74;
lv_obj_t * ui_Label75;
lv_obj_t * ui_Label76;
lv_obj_t * ui_Label77;
lv_obj_t * ui_Label78;
lv_obj_t * ui_Label79;
lv_obj_t * ui_Label80;

// Image definition
lv_obj_t * ui_Image46;
lv_obj_t * ui_Image47;
lv_obj_t * ui_Image48;
lv_obj_t * ui_Image49;
lv_obj_t * ui_Image50;
lv_obj_t * ui_Image51;
lv_obj_t * ui_Image52;
lv_obj_t * ui_Image53;
lv_obj_t * ui_Image54;
lv_obj_t * ui_Image55;
lv_obj_t * ui_Image56;
lv_obj_t * ui_Image57;
lv_obj_t * ui_Image58;
lv_obj_t * ui_Image59;
lv_obj_t * ui_Image60;

// slider definition
lv_obj_t * ui_Slider31;
lv_obj_t * ui_Slider32;
lv_obj_t * ui_Slider33;
lv_obj_t * ui_Slider34;
lv_obj_t * ui_Slider35;
lv_obj_t * ui_Slider36;
lv_obj_t * ui_Slider37;
lv_obj_t * ui_Slider38;
lv_obj_t * ui_Slider39;
lv_obj_t * ui_Slider40;

// arc definition
lv_obj_t * ui_Arc31;
lv_obj_t * ui_Arc32;
lv_obj_t * ui_Arc33;
lv_obj_t * ui_Arc34;
lv_obj_t * ui_Arc35;
lv_obj_t * ui_Arc36;
lv_obj_t * ui_Arc37;
lv_obj_t * ui_Arc38;
lv_obj_t * ui_Arc39;
lv_obj_t * ui_Arc40;

// panel init
lv_obj_t * ui_Panel31;
lv_obj_t * ui_Panel32;
lv_obj_t * ui_Panel33;
lv_obj_t * ui_Panel34;
lv_obj_t * ui_Panel35;
lv_obj_t * ui_Panel36;
lv_obj_t * ui_Panel37;
lv_obj_t * ui_Panel38;
lv_obj_t * ui_Panel39;
lv_obj_t * ui_Panel40;

// container init
lv_obj_t * ui_Container31;
lv_obj_t * ui_Container32;
lv_obj_t * ui_Container33;
lv_obj_t * ui_Container34;
lv_obj_t * ui_Container35;
lv_obj_t * ui_Container36;
lv_obj_t * ui_Container37;
lv_obj_t * ui_Container38;
lv_obj_t * ui_Container39;
lv_obj_t * ui_Container40;

lv_obj_t * ui____initial_actions0;



///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Screen1_screen_init();
    ui_Screen2_screen_init();
    ui_Screen3_screen_init();
    ui_Screen4_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Screen4);
}
