// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;

// label definition
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui_Label13;
extern lv_obj_t * ui_Label14;
extern lv_obj_t * ui_Label15;
extern lv_obj_t * ui_Label16;
extern lv_obj_t * ui_Label17;
extern lv_obj_t * ui_Label18;
extern lv_obj_t * ui_Label19;
extern lv_obj_t * ui_Label20;

// Image definition
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_Image3;
extern lv_obj_t * ui_Image4;
extern lv_obj_t * ui_Image5;
extern lv_obj_t * ui_Image6;
extern lv_obj_t * ui_Image7;
extern lv_obj_t * ui_Image8;
extern lv_obj_t * ui_Image9;
extern lv_obj_t * ui_Image10;
extern lv_obj_t * ui_Image11;
extern lv_obj_t * ui_Image12;
extern lv_obj_t * ui_Image13;
extern lv_obj_t * ui_Image14;
extern lv_obj_t * ui_Image15;

// slider definition
extern lv_obj_t * ui_Slider1;
extern lv_obj_t * ui_Slider2;
extern lv_obj_t * ui_Slider3;
extern lv_obj_t * ui_Slider4;
extern lv_obj_t * ui_Slider5;
extern lv_obj_t * ui_Slider6;
extern lv_obj_t * ui_Slider7;
extern lv_obj_t * ui_Slider8;
extern lv_obj_t * ui_Slider9;
extern lv_obj_t * ui_Slider10;

// arc definition
extern lv_obj_t * ui_Arc1;
extern lv_obj_t * ui_Arc2;
extern lv_obj_t * ui_Arc3;
extern lv_obj_t * ui_Arc4;
extern lv_obj_t * ui_Arc5;
extern lv_obj_t * ui_Arc6;
extern lv_obj_t * ui_Arc7;
extern lv_obj_t * ui_Arc8;
extern lv_obj_t * ui_Arc9;
extern lv_obj_t * ui_Arc10;

// panel init
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_Panel4;
extern lv_obj_t * ui_Panel5;
extern lv_obj_t * ui_Panel6;
extern lv_obj_t * ui_Panel7;
extern lv_obj_t * ui_Panel8;
extern lv_obj_t * ui_Panel9;
extern lv_obj_t * ui_Panel10;

// container init
extern lv_obj_t * ui_Container1;
extern lv_obj_t * ui_Container2;
extern lv_obj_t * ui_Container3;
extern lv_obj_t * ui_Container4;
extern lv_obj_t * ui_Container5;
extern lv_obj_t * ui_Container6;
extern lv_obj_t * ui_Container7;
extern lv_obj_t * ui_Container8;
extern lv_obj_t * ui_Container9;
extern lv_obj_t * ui_Container10;

// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
extern lv_obj_t * ui_Screen2;

// label definition
extern lv_obj_t * ui_Label21;
extern lv_obj_t * ui_Label22;
extern lv_obj_t * ui_Label23;
extern lv_obj_t * ui_Label24;
extern lv_obj_t * ui_Label25;
extern lv_obj_t * ui_Label26;
extern lv_obj_t * ui_Label27;
extern lv_obj_t * ui_Label28;
extern lv_obj_t * ui_Label29;
extern lv_obj_t * ui_Label30;
extern lv_obj_t * ui_Label31;
extern lv_obj_t * ui_Label32;
extern lv_obj_t * ui_Label33;
extern lv_obj_t * ui_Label34;
extern lv_obj_t * ui_Label35;
extern lv_obj_t * ui_Label36;
extern lv_obj_t * ui_Label37;
extern lv_obj_t * ui_Label38;
extern lv_obj_t * ui_Label39;
extern lv_obj_t * ui_Label40;

// Image definition
extern lv_obj_t * ui_Image16;
extern lv_obj_t * ui_Image17;
extern lv_obj_t * ui_Image18;
extern lv_obj_t * ui_Image19;
extern lv_obj_t * ui_Image20;
extern lv_obj_t * ui_Image21;
extern lv_obj_t * ui_Image22;
extern lv_obj_t * ui_Image23;
extern lv_obj_t * ui_Image24;
extern lv_obj_t * ui_Image25;
extern lv_obj_t * ui_Image26;
extern lv_obj_t * ui_Image27;
extern lv_obj_t * ui_Image28;
extern lv_obj_t * ui_Image29;
extern lv_obj_t * ui_Image30;


// slider definition
extern lv_obj_t * ui_Slider11;
extern lv_obj_t * ui_Slider12;
extern lv_obj_t * ui_Slider13;
extern lv_obj_t * ui_Slider14;
extern lv_obj_t * ui_Slider15;
extern lv_obj_t * ui_Slider16;
extern lv_obj_t * ui_Slider17;
extern lv_obj_t * ui_Slider18;
extern lv_obj_t * ui_Slider19;
extern lv_obj_t * ui_Slider20;

// arc definition
extern lv_obj_t * ui_Arc11;
extern lv_obj_t * ui_Arc12;
extern lv_obj_t * ui_Arc13;
extern lv_obj_t * ui_Arc14;
extern lv_obj_t * ui_Arc15;
extern lv_obj_t * ui_Arc16;
extern lv_obj_t * ui_Arc17;
extern lv_obj_t * ui_Arc18;
extern lv_obj_t * ui_Arc19;
extern lv_obj_t * ui_Arc20;

// panel init
extern lv_obj_t * ui_Panel11;
extern lv_obj_t * ui_Panel12;
extern lv_obj_t * ui_Panel13;
extern lv_obj_t * ui_Panel14;
extern lv_obj_t * ui_Panel15;
extern lv_obj_t * ui_Panel16;
extern lv_obj_t * ui_Panel17;
extern lv_obj_t * ui_Panel18;
extern lv_obj_t * ui_Panel19;
extern lv_obj_t * ui_Panel20;

// container init
extern lv_obj_t * ui_Container11;
extern lv_obj_t * ui_Container12;
extern lv_obj_t * ui_Container13;
extern lv_obj_t * ui_Container14;
extern lv_obj_t * ui_Container15;
extern lv_obj_t * ui_Container16;
extern lv_obj_t * ui_Container17;
extern lv_obj_t * ui_Container18;
extern lv_obj_t * ui_Container19;
extern lv_obj_t * ui_Container20;


// SCREEN: ui_Screen3
void ui_Screen3_screen_init(void);
extern lv_obj_t * ui_Screen3;

// label definition
extern lv_obj_t * ui_Label41;
extern lv_obj_t * ui_Label42;
extern lv_obj_t * ui_Label43;
extern lv_obj_t * ui_Label44;
extern lv_obj_t * ui_Label45;
extern lv_obj_t * ui_Label46;
extern lv_obj_t * ui_Label47;
extern lv_obj_t * ui_Label48;
extern lv_obj_t * ui_Label49;
extern lv_obj_t * ui_Label50;
extern lv_obj_t * ui_Label51;
extern lv_obj_t * ui_Label52;
extern lv_obj_t * ui_Label53;
extern lv_obj_t * ui_Label54;
extern lv_obj_t * ui_Label55;
extern lv_obj_t * ui_Label56;
extern lv_obj_t * ui_Label57;
extern lv_obj_t * ui_Label58;
extern lv_obj_t * ui_Label59;
extern lv_obj_t * ui_Label60;

// Image definition
extern lv_obj_t * ui_Image31;
extern lv_obj_t * ui_Image32;
extern lv_obj_t * ui_Image33;
extern lv_obj_t * ui_Image34;
extern lv_obj_t * ui_Image35;
extern lv_obj_t * ui_Image36;
extern lv_obj_t * ui_Image37;
extern lv_obj_t * ui_Image38;
extern lv_obj_t * ui_Image39;
extern lv_obj_t * ui_Image40;
extern lv_obj_t * ui_Image41;
extern lv_obj_t * ui_Image42;
extern lv_obj_t * ui_Image43;
extern lv_obj_t * ui_Image44;
extern lv_obj_t * ui_Image45;

// slider definition
extern lv_obj_t * ui_Slider21;
extern lv_obj_t * ui_Slider22;
extern lv_obj_t * ui_Slider23;
extern lv_obj_t * ui_Slider24;
extern lv_obj_t * ui_Slider25;
extern lv_obj_t * ui_Slider26;
extern lv_obj_t * ui_Slider27;
extern lv_obj_t * ui_Slider28;
extern lv_obj_t * ui_Slider29;
extern lv_obj_t * ui_Slider30;

// arc definition
extern lv_obj_t * ui_Arc21;
extern lv_obj_t * ui_Arc22;
extern lv_obj_t * ui_Arc23;
extern lv_obj_t * ui_Arc24;
extern lv_obj_t * ui_Arc25;
extern lv_obj_t * ui_Arc26;
extern lv_obj_t * ui_Arc27;
extern lv_obj_t * ui_Arc28;
extern lv_obj_t * ui_Arc29;
extern lv_obj_t * ui_Arc30;

// panel init
extern lv_obj_t * ui_Panel21;
extern lv_obj_t * ui_Panel22;
extern lv_obj_t * ui_Panel23;
extern lv_obj_t * ui_Panel24;
extern lv_obj_t * ui_Panel25;
extern lv_obj_t * ui_Panel26;
extern lv_obj_t * ui_Panel27;
extern lv_obj_t * ui_Panel28;
extern lv_obj_t * ui_Panel29;
extern lv_obj_t * ui_Panel30;

// container init
extern lv_obj_t * ui_Container21;
extern lv_obj_t * ui_Container22;
extern lv_obj_t * ui_Container23;
extern lv_obj_t * ui_Container24;
extern lv_obj_t * ui_Container25;
extern lv_obj_t * ui_Container26;
extern lv_obj_t * ui_Container27;
extern lv_obj_t * ui_Container28;
extern lv_obj_t * ui_Container29;
extern lv_obj_t * ui_Container30;

// SCREEN: ui_Screen4
void ui_Screen4_screen_init(void);
extern lv_obj_t * ui_Screen4;

// label definition
extern lv_obj_t * ui_Label61;
extern lv_obj_t * ui_Label62;
extern lv_obj_t * ui_Label63;
extern lv_obj_t * ui_Label64;
extern lv_obj_t * ui_Label65;
extern lv_obj_t * ui_Label66;
extern lv_obj_t * ui_Label67;
extern lv_obj_t * ui_Label68;
extern lv_obj_t * ui_Label69;
extern lv_obj_t * ui_Label70;
extern lv_obj_t * ui_Label71;
extern lv_obj_t * ui_Label72;
extern lv_obj_t * ui_Label73;
extern lv_obj_t * ui_Label74;
extern lv_obj_t * ui_Label75;
extern lv_obj_t * ui_Label76;
extern lv_obj_t * ui_Label77;
extern lv_obj_t * ui_Label78;
extern lv_obj_t * ui_Label79;
extern lv_obj_t * ui_Label80;

// Image definition
extern lv_obj_t * ui_Image46;
extern lv_obj_t * ui_Image47;
extern lv_obj_t * ui_Image48;
extern lv_obj_t * ui_Image49;
extern lv_obj_t * ui_Image50;
extern lv_obj_t * ui_Image51;
extern lv_obj_t * ui_Image52;
extern lv_obj_t * ui_Image53;
extern lv_obj_t * ui_Image54;
extern lv_obj_t * ui_Image55;
extern lv_obj_t * ui_Image56;
extern lv_obj_t * ui_Image57;
extern lv_obj_t * ui_Image58;
extern lv_obj_t * ui_Image59;
extern lv_obj_t * ui_Image60;

// slider definition
extern lv_obj_t * ui_Slider31;
extern lv_obj_t * ui_Slider32;
extern lv_obj_t * ui_Slider33;
extern lv_obj_t * ui_Slider34;
extern lv_obj_t * ui_Slider35;
extern lv_obj_t * ui_Slider36;
extern lv_obj_t * ui_Slider37;
extern lv_obj_t * ui_Slider38;
extern lv_obj_t * ui_Slider39;
extern lv_obj_t * ui_Slider40;

// arc definition
extern lv_obj_t * ui_Arc31;
extern lv_obj_t * ui_Arc32;
extern lv_obj_t * ui_Arc33;
extern lv_obj_t * ui_Arc34;
extern lv_obj_t * ui_Arc35;
extern lv_obj_t * ui_Arc36;
extern lv_obj_t * ui_Arc37;
extern lv_obj_t * ui_Arc38;
extern lv_obj_t * ui_Arc39;
extern lv_obj_t * ui_Arc40;

// panel init
extern lv_obj_t * ui_Panel31;
extern lv_obj_t * ui_Panel32;
extern lv_obj_t * ui_Panel33;
extern lv_obj_t * ui_Panel34;
extern lv_obj_t * ui_Panel35;
extern lv_obj_t * ui_Panel36;
extern lv_obj_t * ui_Panel37;
extern lv_obj_t * ui_Panel38;
extern lv_obj_t * ui_Panel39;
extern lv_obj_t * ui_Panel40;

// container init
extern lv_obj_t * ui_Container31;
extern lv_obj_t * ui_Container32;
extern lv_obj_t * ui_Container33;
extern lv_obj_t * ui_Container34;
extern lv_obj_t * ui_Container35;
extern lv_obj_t * ui_Container36;
extern lv_obj_t * ui_Container37;
extern lv_obj_t * ui_Container38;
extern lv_obj_t * ui_Container39;
extern lv_obj_t * ui_Container40;

extern lv_obj_t * ui____initial_actions0;






LV_IMG_DECLARE(ui_img_1292147816);    // assets\charger (3).png
LV_IMG_DECLARE(ui_img_signal_png);    // assets\signal.png
LV_IMG_DECLARE(ui_img_car_png);    // assets\car.png
LV_IMG_DECLARE(ui_img_live_png ); 
LV_IMG_DECLARE(ui_img_appstore_png); 
LV_IMG_DECLARE(ui_img_playstore_png);
LV_IMG_DECLARE(ui_img_5inclogo2_png);
//LV_IMG_DECLARE(ui_img_bluetech_turquoise_shadow_png);
LV_FONT_DECLARE(ui_font_Font1);
LV_FONT_DECLARE(ui_font_fontAHMER);
LV_FONT_DECLARE(ui_font_Font12);
LV_FONT_DECLARE(ui_font_Fontabdul);
LV_FONT_DECLARE(ui_font_Font_Abduleao_mon6);
LV_FONT_DECLARE(ui_font_Font_Abduleao_mon7);
LV_FONT_DECLARE(ui_font_Font_Abduleao_mon8);
LV_FONT_DECLARE(ui_font_Font_Abduleao_mon9);
LV_FONT_DECLARE(ui_font_Font_Abduleao_mon10);
LV_FONT_DECLARE(ui_font_Font_Abduleao_mon11);
LV_FONT_DECLARE(ui_font_Font_Abduleao_mon12);
LV_FONT_DECLARE(ui_font_Font_Abduleao_mon13);
LV_FONT_DECLARE(ui_font_Font_Abduleao_mon14);
LV_FONT_DECLARE(ui_font_Font_Abduleao_mon15);
LV_FONT_DECLARE(ui_font_Font_Abduleao_mon16);
LV_FONT_DECLARE(ui_font_Font_Abduleao_mon17);
LV_FONT_DECLARE(ui_font_Font_Abduleao_mon18);
LV_FONT_DECLARE(ui_font_Font_Abduleao_mon19);
LV_FONT_DECLARE(ui_font_Font_Abduleao_mon20);
LV_FONT_DECLARE(ui_font_Font_Abduleao_mon21);
LV_FONT_DECLARE(ui_font_Font_Abduleao_mon22);
LV_FONT_DECLARE(ui_font_Font_Abduleao_mon23);
LV_FONT_DECLARE(ui_font_Font_Abduleao_mon24);
LV_FONT_DECLARE(ui_font_Font_Abduleao_mon25);
LV_FONT_DECLARE(ui_font_Font_Abduleao_mon26);
LV_FONT_DECLARE(ui_font_Font_Abduleao_mon27);
LV_FONT_DECLARE(ui_font_Font_Abduleao_mon28);
LV_FONT_DECLARE(ui_font_Font_Abduleao_mon29);
LV_FONT_DECLARE(ui_font_Font_Abduleao_mon30);
LV_FONT_DECLARE(ui_font_Font_Abduleao_mon31);
LV_FONT_DECLARE(ui_font_Font_Abduleao_mon32);
LV_FONT_DECLARE(ui_font_Font_Abduleao_mon33);
LV_FONT_DECLARE(ui_font_Font_Abduleao_mon34);
LV_FONT_DECLARE(ui_font_Font_Abduleao_mon35);
LV_FONT_DECLARE(ui_font_Font_Abduleao_mon36);
LV_FONT_DECLARE(ui_font_Font_Abduleao_mon37);
LV_FONT_DECLARE(ui_font_Font_Abduleao_mon38);
LV_FONT_DECLARE(ui_font_Font_Abduleao_mon39);
LV_FONT_DECLARE(ui_font_Font_Abduleao_mon40);
void ui_init(void);


#ifdef __cplusplus
} /*extern "C"*/


#endif

#endif
