// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"

void ui_Screen3_screen_init(void)
{
    ui_Screen3 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen3, lv_color_hex(0x090909), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    

    /*
          WARNING (for Screen3):
   Use ONLY the following UI elements on Screen3 — otherwise, the modular structure will break.
   - Labels:  ui_Label41 … ui_Label60
   - Images:  ui_Image31 … ui_Image45
   - Arcs:    ui_Arc21 … ui_Arc30
   - Sliders: ui_Slider21 … ui_Slider30
   - Panels:  ui_Panel21 … ui_Panel30
   - Containers: ui_Container21-ui_Container30
   NOTE: Screens 1, 2, and 4 have their own dedicated elements.
   Do NOT reuse or reference them in Screen3.

   Fonts:
   Use ui_font_Font_Abduleao_mon6 – ui_font_Font_Abduleao_mon40 
   (supports both Turkish and European characters).
    */

    // labels

    ui_Label41 = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_Label41, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label41, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label41, 9);
    lv_obj_set_y(ui_Label41, -182);
    lv_obj_set_align(ui_Label41, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label41, "BLUETECH ");
    lv_obj_set_style_text_color(ui_Label41, lv_color_hex(0xFDF9F9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label41, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_Label41, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_Label41, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label41, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);


    ui_Label42 = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_Label42, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label42, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label42, -279);
    lv_obj_set_y(ui_Label42, 197);
    lv_obj_set_align(ui_Label42, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label42, "GÜÇ:");
    lv_obj_set_style_text_color(ui_Label42, lv_color_hex(0xF6F1F1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label42, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label42, &ui_font_Font_Abduleao_mon28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label43 = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_Label43, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label43, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label43, 232);
    lv_obj_set_y(ui_Label43, 197);
    lv_obj_set_align(ui_Label43, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label43, "ENERJİ:");
    lv_obj_set_style_text_color(ui_Label43, lv_color_hex(0xF9F1F1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label43, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label43, &ui_font_Font_Abduleao_mon28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label44 = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_Label44, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label44, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label44, -16);
    lv_obj_set_y(ui_Label44, 126);
    lv_obj_set_align(ui_Label44, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label44, "ZAMAN:");
    lv_obj_set_style_text_color(ui_Label44, lv_color_hex(0xF9F3F3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label44, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label44, &ui_font_Font_Abduleao_mon28, LV_PART_MAIN | LV_STATE_DEFAULT);


    // images 

    ui_Image31 = lv_img_create(ui_Screen3);
    lv_img_set_src(ui_Image31, &ui_img_5inclogo2_png);
    //setLogoSource(ui_Image31);
    lv_obj_set_width(ui_Image31, LV_SIZE_CONTENT);   /// 128
    lv_obj_set_height(ui_Image31, LV_SIZE_CONTENT);    /// 128
    lv_obj_set_x(ui_Image31, -21);
    lv_obj_set_y(ui_Image31, -185);
    lv_obj_set_align(ui_Image31, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image31, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image31, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image31, 200);

    ui_Image32 = lv_img_create(ui_Screen3);
    lv_img_set_src(ui_Image32, &ui_img_car_png);
    lv_obj_set_width(ui_Image32, LV_SIZE_CONTENT);   /// 128
    lv_obj_set_height(ui_Image32, LV_SIZE_CONTENT);    /// 128
    lv_obj_set_x(ui_Image32, 3);
    lv_obj_set_y(ui_Image32, 4);
    lv_obj_set_align(ui_Image32, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image32, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image32, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image32, 600);


 

   
}// WARNING: Use only Label41–60, Image31–45, Arc21–30, Slider21–30, Panel21–30,Container21-30 on Screen3. Fonts: Use ui_font_Font_Abduleao_mon6–ui_font_Font_Abduleao_mon40 (TR & EU support).

