// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"

void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen2, lv_color_hex(0x090909), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
   
   
   /*
          WARNING (for Screen2):
   Use ONLY the following UI elements on Screen2 — otherwise, the modular structure will break.
   - Labels:  ui_Label21 … ui_Label40
   - Images:  ui_Image16 … ui_Image30
   - Arcs:    ui_Arc11 … ui_Arc20
   - Sliders: ui_Slider11 … ui_Slider20
   - Panels:  ui_Panel11 … ui_Panel20
    - Containers: ui_Container11-ui_Container20
   NOTE: Screens 1, 3, and 4 have their own dedicated elements.
   Do NOT reuse or reference them in Screen2.

   Fonts:
   Use ui_font_Font_Abduleao_mon6 – ui_font_Font_Abduleao_mon40 
   (supports both Turkish and European characters).

    */
    
    
    //labels

    ui_Label21 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Label21, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label21, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label21, -6);
    lv_obj_set_y(ui_Label21, -182);
    lv_obj_set_align(ui_Label21, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label21, "BLUETECH ");
    lv_obj_set_style_text_color(ui_Label21, lv_color_hex(0xFCF8F8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label21, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_Label21, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_Label21, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label21, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label22 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Label22, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label22, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label22, -14);
    lv_obj_set_y(ui_Label22, 195);
    lv_obj_set_align(ui_Label22, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label22, "RFID Kartı ya da QR Kodu Okutunuz ");
    lv_obj_set_style_text_color(ui_Label22, lv_color_hex(0xFBF6F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label22, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label22, &ui_font_Font_Abduleao_mon28, LV_PART_MAIN | LV_STATE_DEFAULT);

     // images 
     
    ui_Image16 = lv_img_create(ui_Screen2);
    lv_img_set_src(ui_Image16, &ui_img_5inclogo2_png);
    //setLogoSource(ui_Image16);
    lv_obj_set_width(ui_Image16, LV_SIZE_CONTENT);   /// 128
    lv_obj_set_height(ui_Image16, LV_SIZE_CONTENT);    /// 128
    lv_obj_set_x(ui_Image16, -21);
    lv_obj_set_y(ui_Image16, -185);
    lv_obj_set_align(ui_Image16, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image16, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image16, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image16, 200);

    ui_Image17 = lv_img_create(ui_Screen2);
    lv_img_set_src(ui_Image17, &ui_img_live_png );
    lv_obj_set_width(ui_Image17, LV_SIZE_CONTENT);   /// 512
    lv_obj_set_height(ui_Image17, LV_SIZE_CONTENT);    /// 512
    lv_obj_set_x(ui_Image17, -150);
    lv_obj_set_y(ui_Image17, 3);
    lv_obj_set_align(ui_Image17, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image17, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image17, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image17, 450);




    
}  // WARNING: Use only Label21–40, Image16–30, Arc11–20, Slider11–20, Panel11–20,Container11-20 on Screen2. Fonts: Use ui_font_Font_Abduleao_mon6–ui_font_Font_Abduleao_mon40 (TR & EU support).
