// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"

void ui_Screen1_screen_init(void)
{     

    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x090909), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    

    /*
         WARNING (for Screen1):
   Use ONLY the following UI elements on Screen1 — otherwise, the modular structure will break.
   - Labels:  ui_Label1 … ui_Label20
   - Images:  ui_Image1 … ui_Image15
   - Arcs:    ui_Arc1 … ui_Arc10
   - Sliders: ui_Slider1 … ui_Slider10
   - Panels:  ui_Panel1 … ui_Panel10
   - Containers: ui_Container1-ui_Container10
   NOTE: Screens 2, 3, and 4 have their own dedicated elements.
   Do NOT reuse or reference them in Screen1.

   Fonts:
   Use ui_font_Font_Abduleao_mon6 – ui_font_Font_Abduleao_mon40 
   (supports both Turkish and European characters).
    */

  


    // labels

    ui_Label1 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, 7);
    lv_obj_set_y(ui_Label1, -182);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "BLUETECH ");
    lv_obj_set_style_text_color(ui_Label1, lv_color_hex(0xF7F2F2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_Label1, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_Label1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label1, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, -23);
    lv_obj_set_y(ui_Label2, 180);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "SOKETİ TAKINIZ");
    lv_obj_set_style_text_color(ui_Label2, lv_color_hex(0xF5F0ED), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label2, &ui_font_Font_Abduleao_mon32, LV_PART_MAIN | LV_STATE_DEFAULT);
    
    ui_Label3 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, 300);
    lv_obj_set_y(ui_Label3, 50);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "Mobil Uygulama");
    lv_obj_set_style_text_color(ui_Label3, lv_color_hex(0xF5F0ED), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label3, &ui_font_Font_Abduleao_mon14, LV_PART_MAIN | LV_STATE_DEFAULT);   
    
    ui_Label4 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, -315);
    lv_obj_set_y(ui_Label4, 50);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "Mobil Uygulama");
    lv_obj_set_style_text_color(ui_Label4, lv_color_hex(0xF5F0ED), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label4, &ui_font_Font_Abduleao_mon14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label5 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, -290);
    lv_obj_set_y(ui_Label5, -195);
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "www.celiklerenerji.com");
    lv_obj_set_style_text_color(ui_Label5, lv_color_hex(0xF5F0ED), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label5, &ui_font_Font_Abduleao_mon16, LV_PART_MAIN | LV_STATE_DEFAULT);     
    
    ui_Label6 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label6, -300);
    lv_obj_set_y(ui_Label6, -175);
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "0850 577 1958");
    lv_obj_set_style_text_color(ui_Label6, lv_color_hex(0xF5F0ED), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label6, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label7 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label7, 348);
    lv_obj_set_y(ui_Label7, -182);
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "Kritik");
    lv_obj_set_style_text_color(ui_Label7, lv_color_hex(0xF30F0F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label7, &ui_font_Font_Abduleao_mon12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label8 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label8, 363);
    lv_obj_set_y(ui_Label8, -219);
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "-101");
    lv_obj_set_style_text_color(ui_Label8, lv_color_hex(0xFDFBFB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label9 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label9, 368);
    lv_obj_set_y(ui_Label9, -200);
    lv_obj_set_align(ui_Label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label9, "dBm");
    lv_obj_set_style_text_color(ui_Label9, lv_color_hex(0X075912), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label10 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label10, 335);
    lv_obj_set_y(ui_Label10, -181);
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10, "Ethernet");


     // images 

     ui_Image1 = lv_img_create(ui_Screen1);
    //lv_img_set_src(ui_Image1, &ui_img_5inclogo2_png);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 128
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 128
    lv_obj_set_x(ui_Image1, -21);
    lv_obj_set_y(ui_Image1, -185);
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image1, 200);

    ui_Image2 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image2, &ui_img_1292147816);
    lv_obj_set_width(ui_Image2, LV_SIZE_CONTENT);   /// 128
    lv_obj_set_height(ui_Image2, LV_SIZE_CONTENT);    /// 128
    lv_obj_set_x(ui_Image2, -35);
    lv_obj_set_y(ui_Image2, 10);
    lv_obj_set_align(ui_Image2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image2, 400);

    ui_Image3 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image3, &ui_img_appstore_png);
    lv_obj_set_width(ui_Image3, LV_SIZE_CONTENT);   /// 128
    lv_obj_set_height(ui_Image3, LV_SIZE_CONTENT);    /// 128
    lv_obj_set_x(ui_Image3, -315);
    lv_obj_set_y(ui_Image3, 200);
    lv_obj_set_align(ui_Image3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image3, 200);
 
    ui_Image4 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image4, &ui_img_playstore_png);
    lv_obj_set_width(ui_Image4, LV_SIZE_CONTENT);   /// 128
    lv_obj_set_height(ui_Image4, LV_SIZE_CONTENT);    /// 128
    lv_obj_set_x(ui_Image4, 300);
    lv_obj_set_y(ui_Image4, 200);
    lv_obj_set_align(ui_Image4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image4, 200);

    
   // panels

    ui_Panel1 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel1, 7);
    lv_obj_set_height(ui_Panel1, 10);
    lv_obj_set_x(ui_Panel1, 321);
    lv_obj_set_y(ui_Panel1, -200);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel1, lv_color_hex(0xF9F3F3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel1, lv_color_hex(0x186DAA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);


    
    ui_Panel2 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel2, 7);
    lv_obj_set_height(ui_Panel2, 16);
    lv_obj_set_x(ui_Panel2, 328);
    lv_obj_set_y(ui_Panel2, -203);
    lv_obj_set_align(ui_Panel2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_Panel2, lv_color_hex(0x186DAA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_Panel3 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel3, 7);
    lv_obj_set_height(ui_Panel3, 22);
    lv_obj_set_x(ui_Panel3, 335);
    lv_obj_set_y(ui_Panel3, -206);
    lv_obj_set_align(ui_Panel3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel3, lv_color_hex(0xFBF9F9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel3, lv_color_hex(0x186DAA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
 

    ui_Panel4 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel4, 7);
    lv_obj_set_height(ui_Panel4, 27);
    lv_obj_set_x(ui_Panel4, 342);
    lv_obj_set_y(ui_Panel4, -209);
    lv_obj_set_align(ui_Panel4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel4, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_Panel4, lv_color_hex(0xFAF5F5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel4, lv_color_hex(0x186DAA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    
    //   Arc 

    ui_Arc1 = lv_arc_create(ui_Screen1);
    lv_obj_set_width(ui_Arc1, 37);
    lv_obj_set_height(ui_Arc1, 7);
    lv_obj_set_x(ui_Arc1, 341);
    lv_obj_set_y(ui_Arc1, -201);
    lv_obj_set_align(ui_Arc1, LV_ALIGN_CENTER);
    lv_arc_set_value(ui_Arc1, 1);
    lv_arc_set_bg_angles(ui_Arc1, 0, 360);
    lv_arc_set_rotation(ui_Arc1, 90);
    lv_obj_set_style_arc_color(ui_Arc1, lv_color_hex(0xF7F7FA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Arc1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_Arc1, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_Arc1, false, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_width(ui_Arc1, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_Arc1, 0, LV_PART_KNOB | LV_STATE_DEFAULT);



    ui_Arc2 = lv_arc_create(ui_Screen1);
    lv_obj_set_width(ui_Arc2, 25);
    lv_obj_set_height(ui_Arc2, 26);
    lv_obj_set_x(ui_Arc2, 326);
    lv_obj_set_y(ui_Arc2, -198);
    lv_obj_set_align(ui_Arc2, LV_ALIGN_CENTER);
    lv_arc_set_value(ui_Arc2, 1);
    lv_arc_set_bg_angles(ui_Arc2, 130, 230);
    lv_arc_set_rotation(ui_Arc2, 90);
    lv_obj_set_style_arc_color(ui_Arc2, lv_color_hex(0xF7F7FA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Arc2,255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_Arc2, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_Arc2, false, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_width(ui_Arc2, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_Arc2, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Arc3 = lv_arc_create(ui_Screen1);
    lv_obj_set_width(ui_Arc3, 37);
    lv_obj_set_height(ui_Arc3, 50);
    lv_obj_set_x(ui_Arc3, 326);
    lv_obj_set_y(ui_Arc3, -193);
    lv_obj_set_align(ui_Arc3, LV_ALIGN_CENTER);
    lv_arc_set_value(ui_Arc3, 1);
    lv_arc_set_bg_angles(ui_Arc3, 130, 230);
    lv_arc_set_rotation(ui_Arc3, 90);
    lv_obj_set_style_arc_color(ui_Arc3, lv_color_hex(0xF7F7FA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Arc3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_Arc3, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_Arc3, false, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_width(ui_Arc3, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_Arc3, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Arc4 = lv_arc_create(ui_Screen1);
    lv_obj_set_width(ui_Arc4, 51);
    lv_obj_set_height(ui_Arc4, 72);
    lv_obj_set_x(ui_Arc4, 326);
    lv_obj_set_y(ui_Arc4, -189);
    lv_obj_set_align(ui_Arc4, LV_ALIGN_CENTER);
    lv_arc_set_value(ui_Arc4, 1);
    lv_arc_set_bg_angles(ui_Arc4, 130, 230);
    lv_arc_set_rotation(ui_Arc4, 90);
    lv_obj_set_style_arc_color(ui_Arc4, lv_color_hex(0xF7F7FA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Arc4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_Arc4, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_Arc4, false, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_width(ui_Arc4, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_Arc4, 0, LV_PART_KNOB | LV_STATE_DEFAULT);


    // Containers
    
    
    ui_Container1 = lv_obj_create(ui_Screen1);
    lv_obj_remove_style_all(ui_Container1);
    lv_obj_set_width(ui_Container1, 54);
    lv_obj_set_height(ui_Container1, 38);
    lv_obj_set_x(ui_Container1, 335);
    lv_obj_set_y(ui_Container1, -210);
    lv_obj_set_align(ui_Container1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Container1, lv_color_hex(0x242827), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Container1, lv_color_hex(0xF4F8F9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Container1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Container1, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
 
    ui_Container2 = lv_obj_create(ui_Screen1);
    lv_obj_remove_style_all(ui_Container2);
    lv_obj_set_width(ui_Container2, 13);
    lv_obj_set_height(ui_Container2, 11);
    lv_obj_set_x(ui_Container2, 320);
    lv_obj_set_y(ui_Container2, -201);
    lv_obj_set_align(ui_Container2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Container2, lv_color_hex(0x0EF348), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    
    ui_Container3 = lv_obj_create(ui_Screen1);
    lv_obj_remove_style_all(ui_Container3);
    lv_obj_set_width(ui_Container3, 13);
    lv_obj_set_height(ui_Container3, 11);
    lv_obj_set_x(ui_Container3, 349);
    lv_obj_set_y(ui_Container3, -201);
    lv_obj_set_align(ui_Container3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Container3, lv_color_hex(0xFA9906), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    
} // WARNING: Use only Label1–20, Image1–15, Arc1–10, Slider1–10, Panel1–10,Container1-10 on Screen1. Fonts: Use ui_font_Font_Abduleao_mon6–ui_font_Font_Abduleao_mon40 (TR & EU support).

