// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"

void ui_Screen4_screen_init(void)
{
    ui_Screen4 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen4, lv_color_hex(0x090909), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    

     /*
      WARNING (for Screen4):
   Use ONLY the following UI elements on Screen4 — otherwise, the modular structure will break.
   - Labels:  ui_Label61 … ui_Label80
   - Images:  ui_Image46 … ui_Image60
   - Arcs:    ui_Arc31 … ui_Arc40
   - Sliders: ui_Slider31 … ui_Slider40
   - Panels:  ui_Panel31 … ui_Panel40
   - Containers: ui_Container31-ui_Container40
   NOTE: Screens 1, 2, and 3 have their own dedicated elements.
   Do NOT reuse or reference them in Screen4.

   Fonts:
   Use ui_font_Font_Abduleao_mon6 – ui_font_Font_Abduleao_mon40 
   (supports both Turkish and European characters).
    */

     // labels
     
    ui_Label61 = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_Label61, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label61, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label61, 7);
    lv_obj_set_y(ui_Label61, -169);
    lv_obj_set_align(ui_Label61, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label61, "BLUETECH ");
    lv_obj_set_style_text_color(ui_Label61, lv_color_hex(0xF7F2F2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label61, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_Label61, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_Label61, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label61, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);
    
    ui_Label62 = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_Label62, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label62, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label62, 1);
    lv_obj_set_y(ui_Label62, 12);
    lv_obj_set_align(ui_Label62, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label62, "SİSTEM YÜKLENİYOR...");//SCREEN MESSAGE
    lv_obj_set_style_text_color(ui_Label62, lv_color_hex(0xFBF3F3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label62, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label62, &ui_font_Font_Abduleao_mon28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label63 = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_Label63, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label63, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label63, -14);
    lv_obj_set_y(ui_Label63, 100);
    lv_obj_set_align(ui_Label63, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label63, "");//RFİD UPDATE
    lv_obj_set_style_text_color(ui_Label63, lv_color_hex(0xFBF3F3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label63, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label63, &ui_font_Font_Abduleao_mon28, LV_PART_MAIN | LV_STATE_DEFAULT);


    ui_Label64 = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_Label64, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label64, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label64, -49);
    lv_obj_set_y(ui_Label64, -86);
    lv_obj_set_align(ui_Label64, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label64, "");//FIRMWARE UPDATE
    lv_obj_set_style_text_color(ui_Label64, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label64, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label64, &ui_font_Font_Abduleao_mon16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label65 = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_Label65, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label65, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label65, -156);
    lv_obj_set_y(ui_Label65, -22);
    lv_obj_set_align(ui_Label65, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label65, "");//41%
    lv_obj_set_style_text_color(ui_Label65, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label65, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    

     ui_Label66 = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_Label66, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label66, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label66, -51);
    lv_obj_set_y(ui_Label66, -60);
    lv_obj_set_align(ui_Label66, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label66, "");//verText=V002
    lv_obj_set_style_text_color(ui_Label66, lv_color_hex(0x8C93A4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label66, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label67 = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_Label67, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label67, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label67, 23);
    lv_obj_set_y(ui_Label67, -24);
    lv_obj_set_align(ui_Label67, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label67, "");// Downloaded 1.2MB/1.56MB
    lv_obj_set_style_text_color(ui_Label67, lv_color_hex(0x29BC7B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label67, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    
    ui_Label68 = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_Label68, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label68, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label68, -41);
    lv_obj_set_y(ui_Label68, 10);
    lv_obj_set_align(ui_Label68, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label68, "");//Time remaning...
    lv_obj_set_style_text_color(ui_Label68, lv_color_hex(0xF1E4E4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label68, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label69 = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_Label69, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label69, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label69, 287);
    lv_obj_set_y(ui_Label69, 213);
    lv_obj_set_align(ui_Label69, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label69, "");//MAC

   //images

    ui_Image46 = lv_img_create(ui_Screen4);
    lv_img_set_src(ui_Image46, &ui_img_5inclogo2_png);
    //setLogoSource(ui_Image46);
    lv_obj_set_width(ui_Image46, LV_SIZE_CONTENT);   /// 128
    lv_obj_set_height(ui_Image46, LV_SIZE_CONTENT);    /// 128
    lv_obj_set_x(ui_Image46, -21);
    lv_obj_set_y(ui_Image46, -185);
    lv_obj_set_align(ui_Image46, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image46, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image46, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image46, 200);



    // arc,slider

    ui_Arc31= lv_arc_create(ui_Screen4);
    lv_obj_set_size(ui_Arc31, 90, 90);
    lv_obj_align(ui_Arc31, LV_ALIGN_CENTER, -156, -21);
    lv_arc_set_range(ui_Arc31, 0, 100);
    lv_arc_set_value(ui_Arc31, 1);
    lv_arc_set_bg_angles(ui_Arc31, 0, 360);
    lv_arc_set_rotation(ui_Arc31, 90);
    lv_obj_set_style_arc_color(ui_Arc31, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa  (ui_Arc31, LV_OPA_COVER,         LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_Arc31, 10,                    LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_color(ui_Arc31, lv_color_hex(0xA62412), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa  (ui_Arc31, LV_OPA_COVER,          LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_Arc31, 10,                     LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Arc31, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_add_flag(ui_Arc31, LV_OBJ_FLAG_HIDDEN);

    ui_Slider31= lv_slider_create(ui_Screen4);
    lv_slider_set_value(ui_Slider31, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Slider31) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Slider31, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Slider31, 316);
    lv_obj_set_height(ui_Slider31, 7);
    lv_obj_set_x(ui_Slider31, 0);
    lv_obj_set_y(ui_Slider31, 37);
    lv_obj_set_align(ui_Slider31, LV_ALIGN_CENTER);

    lv_obj_set_style_bg_color(ui_Slider31, lv_color_hex(0x66FF00), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider31, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Slider31, lv_color_hex(0x120303), LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Slider31, lv_color_hex(0x909090), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider31, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Slider31, lv_color_hex(0x808080), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_add_flag(ui_Slider31, LV_OBJ_FLAG_HIDDEN);




 
}// WARNING: Use only Label61–80, Image46–60, Arc31–40, Slider31–40, Panel31–40,Container31-40 on Screen4. Fonts: Use ui_font_Font_Abduleao_mon6–ui_font_Font_Abduleao_mon40 (TR & EU support).

